# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceImpedSpec.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1142, 645)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.layout_equip_connection = QtGui.QVBoxLayout()
        self.layout_equip_connection.setObjectName(_fromUtf8("layout_equip_connection"))
        self.layout_detect_pyvisa = QtGui.QHBoxLayout()
        self.layout_detect_pyvisa.setObjectName(_fromUtf8("layout_detect_pyvisa"))
        self.btn_detectar = QtGui.QPushButton(self.groupBox)
        self.btn_detectar.setObjectName(_fromUtf8("btn_detectar"))
        self.layout_detect_pyvisa.addWidget(self.btn_detectar)
        self.checkbox_pyvisasim = QtGui.QCheckBox(self.groupBox)
        self.checkbox_pyvisasim.setObjectName(_fromUtf8("checkbox_pyvisasim"))
        self.layout_detect_pyvisa.addWidget(self.checkbox_pyvisasim)
        self.layout_equip_connection.addLayout(self.layout_detect_pyvisa)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.combobox_equipamentos = QtGui.QComboBox(self.groupBox)
        self.combobox_equipamentos.setObjectName(_fromUtf8("combobox_equipamentos"))
        self.horizontalLayout_4.addWidget(self.combobox_equipamentos)
        self.btn_conectar = QtGui.QPushButton(self.groupBox)
        self.btn_conectar.setMaximumSize(QtCore.QSize(76, 16777215))
        self.btn_conectar.setObjectName(_fromUtf8("btn_conectar"))
        self.horizontalLayout_4.addWidget(self.btn_conectar)
        self.layout_equip_connection.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.label_inst_name = QtGui.QLabel(self.groupBox)
        self.label_inst_name.setMinimumSize(QtCore.QSize(151, 0))
        self.label_inst_name.setText(_fromUtf8(""))
        self.label_inst_name.setObjectName(_fromUtf8("label_inst_name"))
        self.verticalLayout_3.addWidget(self.label_inst_name)
        self.layout_equip_connection.addLayout(self.verticalLayout_3)
        self.gridLayout_5.addLayout(self.layout_equip_connection, 0, 0, 1, 1)
        self.group_calibration = QtGui.QGroupBox(self.tab)
        self.group_calibration.setEnabled(False)
        self.group_calibration.setGeometry(QtCore.QRect(10, 380, 321, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.group_calibration.sizePolicy().hasHeightForWidth())
        self.group_calibration.setSizePolicy(sizePolicy)
        self.group_calibration.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.group_calibration.setAutoFillBackground(False)
        self.group_calibration.setObjectName(_fromUtf8("group_calibration"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.group_calibration)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btn_shortcal = QtGui.QPushButton(self.group_calibration)
        self.btn_shortcal.setObjectName(_fromUtf8("btn_shortcal"))
        self.horizontalLayout_14.addWidget(self.btn_shortcal)
        self.btn_opencal = QtGui.QPushButton(self.group_calibration)
        self.btn_opencal.setObjectName(_fromUtf8("btn_opencal"))
        self.horizontalLayout_14.addWidget(self.btn_opencal)
        self.blt_skipcal = QtGui.QPushButton(self.group_calibration)
        self.blt_skipcal.setObjectName(_fromUtf8("blt_skipcal"))
        self.horizontalLayout_14.addWidget(self.blt_skipcal)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.groupBox_analise_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_analise_2.setEnabled(False)
        self.groupBox_analise_2.setGeometry(QtCore.QRect(10, 130, 321, 261))
        self.groupBox_analise_2.setObjectName(_fromUtf8("groupBox_analise_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_analise_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.layout_CompParam = QtGui.QVBoxLayout()
        self.layout_CompParam.setObjectName(_fromUtf8("layout_CompParam"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_15 = QtGui.QLabel(self.groupBox_analise_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_13.addWidget(self.label_15)
        self.spin_freq_inicial_2 = QtGui.QSpinBox(self.groupBox_analise_2)
        self.spin_freq_inicial_2.setMinimum(40)
        self.spin_freq_inicial_2.setMaximum(110000000)
        self.spin_freq_inicial_2.setObjectName(_fromUtf8("spin_freq_inicial_2"))
        self.horizontalLayout_13.addWidget(self.spin_freq_inicial_2)
        self.layout_CompParam.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_14 = QtGui.QLabel(self.groupBox_analise_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_12.addWidget(self.label_14)
        self.spin_freq_final_2 = QtGui.QSpinBox(self.groupBox_analise_2)
        self.spin_freq_final_2.setMinimum(40)
        self.spin_freq_final_2.setMaximum(110000000)
        self.spin_freq_final_2.setProperty("value", 110000000)
        self.spin_freq_final_2.setObjectName(_fromUtf8("spin_freq_final_2"))
        self.horizontalLayout_12.addWidget(self.spin_freq_final_2)
        self.layout_CompParam.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_analise_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_16.addWidget(self.label_17)
        self.num_pontos_2 = QtGui.QSpinBox(self.groupBox_analise_2)
        self.num_pontos_2.setMinimum(1)
        self.num_pontos_2.setMaximum(800)
        self.num_pontos_2.setProperty("value", 400)
        self.num_pontos_2.setObjectName(_fromUtf8("num_pontos_2"))
        self.horizontalLayout_16.addWidget(self.num_pontos_2)
        self.layout_CompParam.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_analise_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        self.var_log_2 = QtGui.QRadioButton(self.groupBox_analise_2)
        self.var_log_2.setChecked(True)
        self.var_log_2.setAutoExclusive(True)
        self.var_log_2.setObjectName(_fromUtf8("var_log_2"))
        self.horizontalLayout_15.addWidget(self.var_log_2, 0, QtCore.Qt.AlignLeft)
        self.var_lin_2 = QtGui.QRadioButton(self.groupBox_analise_2)
        self.var_lin_2.setObjectName(_fromUtf8("var_lin_2"))
        self.horizontalLayout_15.addWidget(self.var_lin_2)
        self.layout_CompParam.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_analise_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_18.addWidget(self.label_19)
        self.spinbox_tensao_2 = QtGui.QDoubleSpinBox(self.groupBox_analise_2)
        self.spinbox_tensao_2.setPrefix(_fromUtf8(""))
        self.spinbox_tensao_2.setMaximum(42.0)
        self.spinbox_tensao_2.setSingleStep(0.1)
        self.spinbox_tensao_2.setProperty("value", 0.5)
        self.spinbox_tensao_2.setObjectName(_fromUtf8("spinbox_tensao_2"))
        self.horizontalLayout_18.addWidget(self.spinbox_tensao_2)
        self.layout_CompParam.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_analise_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_17.addWidget(self.label_18)
        self.spinbox_banda_2 = QtGui.QSpinBox(self.groupBox_analise_2)
        self.spinbox_banda_2.setMinimum(1)
        self.spinbox_banda_2.setMaximum(5)
        self.spinbox_banda_2.setProperty("value", 2)
        self.spinbox_banda_2.setObjectName(_fromUtf8("spinbox_banda_2"))
        self.horizontalLayout_17.addWidget(self.spinbox_banda_2)
        self.layout_CompParam.addLayout(self.horizontalLayout_17)
        self.checkbox_ptavg_2 = QtGui.QCheckBox(self.groupBox_analise_2)
        self.checkbox_ptavg_2.setChecked(False)
        self.checkbox_ptavg_2.setObjectName(_fromUtf8("checkbox_ptavg_2"))
        self.layout_CompParam.addWidget(self.checkbox_ptavg_2)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_analise_2)
        self.label_20.setEnabled(False)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_19.addWidget(self.label_20)
        self.spin_ptavg_2 = QtGui.QSpinBox(self.groupBox_analise_2)
        self.spin_ptavg_2.setEnabled(False)
        self.spin_ptavg_2.setMinimum(1)
        self.spin_ptavg_2.setMaximum(256)
        self.spin_ptavg_2.setProperty("value", 2)
        self.spin_ptavg_2.setObjectName(_fromUtf8("spin_ptavg_2"))
        self.horizontalLayout_19.addWidget(self.spin_ptavg_2)
        self.layout_CompParam.addLayout(self.horizontalLayout_19)
        self.verticalLayout_8.addLayout(self.layout_CompParam)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_analise = QtGui.QGroupBox(self.tab_2)
        self.groupBox_analise.setEnabled(False)
        self.groupBox_analise.setGeometry(QtCore.QRect(10, 260, 321, 261))
        self.groupBox_analise.setObjectName(_fromUtf8("groupBox_analise"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_analise)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.layout_analysisParam = QtGui.QVBoxLayout()
        self.layout_analysisParam.setObjectName(_fromUtf8("layout_analysisParam"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_4 = QtGui.QLabel(self.groupBox_analise)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.spin_freq_inicial = QtGui.QSpinBox(self.groupBox_analise)
        self.spin_freq_inicial.setMinimum(40)
        self.spin_freq_inicial.setMaximum(110000000)
        self.spin_freq_inicial.setObjectName(_fromUtf8("spin_freq_inicial"))
        self.horizontalLayout_11.addWidget(self.spin_freq_inicial)
        self.layout_analysisParam.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_analise)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.spin_freq_final = QtGui.QSpinBox(self.groupBox_analise)
        self.spin_freq_final.setMinimum(40)
        self.spin_freq_final.setMaximum(110000000)
        self.spin_freq_final.setProperty("value", 110000000)
        self.spin_freq_final.setObjectName(_fromUtf8("spin_freq_final"))
        self.horizontalLayout.addWidget(self.spin_freq_final)
        self.layout_analysisParam.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_analise)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.num_pontos = QtGui.QSpinBox(self.groupBox_analise)
        self.num_pontos.setMinimum(1)
        self.num_pontos.setMaximum(800)
        self.num_pontos.setProperty("value", 400)
        self.num_pontos.setObjectName(_fromUtf8("num_pontos"))
        self.horizontalLayout_5.addWidget(self.num_pontos)
        self.layout_analysisParam.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.groupBox_analise)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.var_log = QtGui.QRadioButton(self.groupBox_analise)
        self.var_log.setChecked(True)
        self.var_log.setAutoExclusive(True)
        self.var_log.setObjectName(_fromUtf8("var_log"))
        self.horizontalLayout_8.addWidget(self.var_log, 0, QtCore.Qt.AlignLeft)
        self.var_lin = QtGui.QRadioButton(self.groupBox_analise)
        self.var_lin.setObjectName(_fromUtf8("var_lin"))
        self.horizontalLayout_8.addWidget(self.var_lin)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_8)
        self.layout_analysisParam.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.groupBox_analise)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.spinbox_tensao = QtGui.QDoubleSpinBox(self.groupBox_analise)
        self.spinbox_tensao.setPrefix(_fromUtf8(""))
        self.spinbox_tensao.setMaximum(42.0)
        self.spinbox_tensao.setSingleStep(0.1)
        self.spinbox_tensao.setProperty("value", 0.5)
        self.spinbox_tensao.setObjectName(_fromUtf8("spinbox_tensao"))
        self.horizontalLayout_3.addWidget(self.spinbox_tensao)
        self.layout_analysisParam.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.groupBox_analise)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.spinbox_banda = QtGui.QSpinBox(self.groupBox_analise)
        self.spinbox_banda.setMinimum(1)
        self.spinbox_banda.setMaximum(5)
        self.spinbox_banda.setProperty("value", 2)
        self.spinbox_banda.setObjectName(_fromUtf8("spinbox_banda"))
        self.horizontalLayout_10.addWidget(self.spinbox_banda)
        self.layout_analysisParam.addLayout(self.horizontalLayout_10)
        self.checkbox_ptavg = QtGui.QCheckBox(self.groupBox_analise)
        self.checkbox_ptavg.setChecked(False)
        self.checkbox_ptavg.setObjectName(_fromUtf8("checkbox_ptavg"))
        self.layout_analysisParam.addWidget(self.checkbox_ptavg)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_analise)
        self.label_10.setEnabled(False)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.spin_ptavg = QtGui.QSpinBox(self.groupBox_analise)
        self.spin_ptavg.setEnabled(False)
        self.spin_ptavg.setMinimum(1)
        self.spin_ptavg.setMaximum(256)
        self.spin_ptavg.setProperty("value", 2)
        self.spin_ptavg.setObjectName(_fromUtf8("spin_ptavg"))
        self.horizontalLayout_9.addWidget(self.spin_ptavg)
        self.layout_analysisParam.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.layout_analysisParam)
        self.groupBox__amostra = QtGui.QGroupBox(self.tab_2)
        self.groupBox__amostra.setEnabled(False)
        self.groupBox__amostra.setGeometry(QtCore.QRect(10, 0, 321, 261))
        self.groupBox__amostra.setObjectName(_fromUtf8("groupBox__amostra"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox__amostra)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.layout_sample = QtGui.QVBoxLayout()
        self.layout_sample.setObjectName(_fromUtf8("layout_sample"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox__amostra)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.amostra_id = QtGui.QLineEdit(self.groupBox__amostra)
        self.amostra_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.amostra_id.setObjectName(_fromUtf8("amostra_id"))
        self.verticalLayout_6.addWidget(self.amostra_id)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.groupBox__amostra)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.LineEdit_SavePath = QtGui.QLineEdit(self.groupBox__amostra)
        self.LineEdit_SavePath.setReadOnly(True)
        self.LineEdit_SavePath.setObjectName(_fromUtf8("LineEdit_SavePath"))
        self.horizontalLayout_6.addWidget(self.LineEdit_SavePath)
        self.toolbtn_savepath = QtGui.QToolButton(self.groupBox__amostra)
        self.toolbtn_savepath.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolbtn_savepath.setArrowType(QtCore.Qt.NoArrow)
        self.toolbtn_savepath.setObjectName(_fromUtf8("toolbtn_savepath"))
        self.horizontalLayout_6.addWidget(self.toolbtn_savepath)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.layout_sample.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_11 = QtGui.QLabel(self.groupBox__amostra)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_4.addWidget(self.label_11)
        self.tbox_diametro = QtGui.QLineEdit(self.groupBox__amostra)
        self.tbox_diametro.setObjectName(_fromUtf8("tbox_diametro"))
        self.verticalLayout_4.addWidget(self.tbox_diametro)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_12 = QtGui.QLabel(self.groupBox__amostra)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_5.addWidget(self.label_12)
        self.tbox_espessura = QtGui.QLineEdit(self.groupBox__amostra)
        self.tbox_espessura.setObjectName(_fromUtf8("tbox_espessura"))
        self.verticalLayout_5.addWidget(self.tbox_espessura)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.layout_sample.addLayout(self.horizontalLayout_7)
        self.layout_notes = QtGui.QVBoxLayout()
        self.layout_notes.setObjectName(_fromUtf8("layout_notes"))
        self.label_13 = QtGui.QLabel(self.groupBox__amostra)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.layout_notes.addWidget(self.label_13)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox__amostra)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.layout_notes.addWidget(self.plainTextEdit)
        self.layout_sample.addLayout(self.layout_notes)
        self.gridLayout_7.addLayout(self.layout_sample, 0, 0, 1, 1)
        self.btn_run = QtGui.QPushButton(self.tab_2)
        self.btn_run.setEnabled(False)
        self.btn_run.setGeometry(QtCore.QRect(20, 510, 301, 23))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.btn_run.setFont(font)
        self.btn_run.setObjectName(_fromUtf8("btn_run"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(330, 1, 781, 411))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_9.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(350, 420, 731, 30))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.Layout_btn_plot = QtGui.QHBoxLayout(self.layoutWidget1)
        self.Layout_btn_plot.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.Layout_btn_plot.setMargin(0)
        self.Layout_btn_plot.setObjectName(_fromUtf8("Layout_btn_plot"))
        self.btn_plot_permi = QtGui.QPushButton(self.layoutWidget1)
        self.btn_plot_permi.setEnabled(False)
        self.btn_plot_permi.setCheckable(True)
        self.btn_plot_permi.setAutoExclusive(False)
        self.btn_plot_permi.setObjectName(_fromUtf8("btn_plot_permi"))
        self.Layout_btn_plot.addWidget(self.btn_plot_permi)
        self.btn_plot_ZT = QtGui.QPushButton(self.layoutWidget1)
        self.btn_plot_ZT.setEnabled(False)
        self.btn_plot_ZT.setCheckable(False)
        self.btn_plot_ZT.setAutoExclusive(False)
        self.btn_plot_ZT.setObjectName(_fromUtf8("btn_plot_ZT"))
        self.Layout_btn_plot.addWidget(self.btn_plot_ZT)
        self.btn_plot_RC = QtGui.QPushButton(self.layoutWidget1)
        self.btn_plot_RC.setEnabled(False)
        self.btn_plot_RC.setCheckable(False)
        self.btn_plot_RC.setAutoExclusive(False)
        self.btn_plot_RC.setObjectName(_fromUtf8("btn_plot_RC"))
        self.Layout_btn_plot.addWidget(self.btn_plot_RC)
        self.btn_plot_ZrZi = QtGui.QPushButton(self.layoutWidget1)
        self.btn_plot_ZrZi.setEnabled(False)
        self.btn_plot_ZrZi.setCheckable(False)
        self.btn_plot_ZrZi.setAutoExclusive(False)
        self.btn_plot_ZrZi.setObjectName(_fromUtf8("btn_plot_ZrZi"))
        self.Layout_btn_plot.addWidget(self.btn_plot_ZrZi)
        self.btn_plot = QtGui.QPushButton(self.layoutWidget1)
        self.btn_plot.setObjectName(_fromUtf8("btn_plot"))
        self.Layout_btn_plot.addWidget(self.btn_plot)
        self.tableView = QtGui.QTableView(self.tab_2)
        self.tableView.setGeometry(QtCore.QRect(350, 460, 731, 100))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 10000000))
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.tableView.raise_()
        self.groupBox__amostra.raise_()
        self.btn_run.raise_()
        self.groupBox_analise.raise_()
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_analise_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_analise_3.setEnabled(True)
        self.groupBox_analise_3.setGeometry(QtCore.QRect(10, 260, 321, 261))
        self.groupBox_analise_3.setAutoFillBackground(True)
        self.groupBox_analise_3.setObjectName(_fromUtf8("groupBox_analise_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_analise_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_29 = QtGui.QLabel(self.groupBox_analise_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_29.addWidget(self.label_29)
        self.spin_freq_inicial_4 = QtGui.QSpinBox(self.groupBox_analise_3)
        self.spin_freq_inicial_4.setMinimum(40)
        self.spin_freq_inicial_4.setMaximum(110000000)
        self.spin_freq_inicial_4.setObjectName(_fromUtf8("spin_freq_inicial_4"))
        self.horizontalLayout_29.addWidget(self.spin_freq_inicial_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_28 = QtGui.QLabel(self.groupBox_analise_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_28.addWidget(self.label_28)
        self.spin_freq_final_4 = QtGui.QSpinBox(self.groupBox_analise_3)
        self.spin_freq_final_4.setMinimum(40)
        self.spin_freq_final_4.setMaximum(110000000)
        self.spin_freq_final_4.setProperty("value", 110000000)
        self.spin_freq_final_4.setObjectName(_fromUtf8("spin_freq_final_4"))
        self.horizontalLayout_28.addWidget(self.spin_freq_final_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_31 = QtGui.QLabel(self.groupBox_analise_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_32.addWidget(self.label_31)
        self.num_pontos_4 = QtGui.QSpinBox(self.groupBox_analise_3)
        self.num_pontos_4.setMinimum(1)
        self.num_pontos_4.setMaximum(800)
        self.num_pontos_4.setProperty("value", 400)
        self.num_pontos_4.setObjectName(_fromUtf8("num_pontos_4"))
        self.horizontalLayout_32.addWidget(self.num_pontos_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_30 = QtGui.QLabel(self.groupBox_analise_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_31.addWidget(self.label_30)
        self.var_log_4 = QtGui.QRadioButton(self.groupBox_analise_3)
        self.var_log_4.setChecked(True)
        self.var_log_4.setAutoExclusive(True)
        self.var_log_4.setObjectName(_fromUtf8("var_log_4"))
        self.horizontalLayout_31.addWidget(self.var_log_4, 0, QtCore.Qt.AlignLeft)
        self.var_lin_4 = QtGui.QRadioButton(self.groupBox_analise_3)
        self.var_lin_4.setObjectName(_fromUtf8("var_lin_4"))
        self.horizontalLayout_31.addWidget(self.var_lin_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_33 = QtGui.QLabel(self.groupBox_analise_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_34.addWidget(self.label_33)
        self.spinbox_tensao_4 = QtGui.QDoubleSpinBox(self.groupBox_analise_3)
        self.spinbox_tensao_4.setPrefix(_fromUtf8(""))
        self.spinbox_tensao_4.setMaximum(42.0)
        self.spinbox_tensao_4.setSingleStep(0.1)
        self.spinbox_tensao_4.setProperty("value", 0.5)
        self.spinbox_tensao_4.setObjectName(_fromUtf8("spinbox_tensao_4"))
        self.horizontalLayout_34.addWidget(self.spinbox_tensao_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_32 = QtGui.QLabel(self.groupBox_analise_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_33.addWidget(self.label_32)
        self.spinbox_banda_4 = QtGui.QSpinBox(self.groupBox_analise_3)
        self.spinbox_banda_4.setMinimum(1)
        self.spinbox_banda_4.setMaximum(5)
        self.spinbox_banda_4.setProperty("value", 2)
        self.spinbox_banda_4.setObjectName(_fromUtf8("spinbox_banda_4"))
        self.horizontalLayout_33.addWidget(self.spinbox_banda_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_33)
        self.checkbox_ptavg_4 = QtGui.QCheckBox(self.groupBox_analise_3)
        self.checkbox_ptavg_4.setChecked(False)
        self.checkbox_ptavg_4.setObjectName(_fromUtf8("checkbox_ptavg_4"))
        self.verticalLayout_13.addWidget(self.checkbox_ptavg_4)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_34 = QtGui.QLabel(self.groupBox_analise_3)
        self.label_34.setEnabled(False)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_35.addWidget(self.label_34)
        self.spin_ptavg_4 = QtGui.QSpinBox(self.groupBox_analise_3)
        self.spin_ptavg_4.setEnabled(False)
        self.spin_ptavg_4.setMinimum(1)
        self.spin_ptavg_4.setMaximum(256)
        self.spin_ptavg_4.setProperty("value", 2)
        self.spin_ptavg_4.setObjectName(_fromUtf8("spin_ptavg_4"))
        self.horizontalLayout_35.addWidget(self.spin_ptavg_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_35)
        self.verticalLayout_10.addLayout(self.verticalLayout_13)
        self.groupBox__amostra_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox__amostra_2.setEnabled(True)
        self.groupBox__amostra_2.setGeometry(QtCore.QRect(10, 0, 321, 261))
        self.groupBox__amostra_2.setObjectName(_fromUtf8("groupBox__amostra_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox__amostra_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_38 = QtGui.QLabel(self.groupBox__amostra_2)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_14.addWidget(self.label_38)
        self.amostra_id_2 = QtGui.QLineEdit(self.groupBox__amostra_2)
        self.amostra_id_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.amostra_id_2.setObjectName(_fromUtf8("amostra_id_2"))
        self.verticalLayout_14.addWidget(self.amostra_id_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_14)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_37 = QtGui.QLabel(self.groupBox__amostra_2)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_37.addWidget(self.label_37)
        self.LineEdit_SavePath_2 = QtGui.QLineEdit(self.groupBox__amostra_2)
        self.LineEdit_SavePath_2.setReadOnly(True)
        self.LineEdit_SavePath_2.setObjectName(_fromUtf8("LineEdit_SavePath_2"))
        self.horizontalLayout_37.addWidget(self.LineEdit_SavePath_2)
        self.toolbtn_savepath_2 = QtGui.QToolButton(self.groupBox__amostra_2)
        self.toolbtn_savepath_2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolbtn_savepath_2.setArrowType(QtCore.Qt.NoArrow)
        self.toolbtn_savepath_2.setObjectName(_fromUtf8("toolbtn_savepath_2"))
        self.horizontalLayout_37.addWidget(self.toolbtn_savepath_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_35 = QtGui.QLabel(self.groupBox__amostra_2)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_11.addWidget(self.label_35)
        self.tbox_diametro_2 = QtGui.QLineEdit(self.groupBox__amostra_2)
        self.tbox_diametro_2.setObjectName(_fromUtf8("tbox_diametro_2"))
        self.verticalLayout_11.addWidget(self.tbox_diametro_2)
        self.horizontalLayout_36.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_36 = QtGui.QLabel(self.groupBox__amostra_2)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_12.addWidget(self.label_36)
        self.tbox_espessura_2 = QtGui.QLineEdit(self.groupBox__amostra_2)
        self.tbox_espessura_2.setObjectName(_fromUtf8("tbox_espessura_2"))
        self.verticalLayout_12.addWidget(self.tbox_espessura_2)
        self.horizontalLayout_36.addLayout(self.verticalLayout_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_36)
        self.label_39 = QtGui.QLabel(self.groupBox__amostra_2)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_7.addWidget(self.label_39)
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.groupBox__amostra_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.verticalLayout_7.addWidget(self.plainTextEdit_2)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.listWidget = QtGui.QListWidget(self.tab_3)
        self.listWidget.setGeometry(QtCore.QRect(350, 10, 391, 461))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.frame = QtGui.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(750, 10, 421, 459))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_45 = QtGui.QLabel(self.frame)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 8, 1, 1, 1)
        self.amostra_id_list = QtGui.QLabel(self.frame)
        self.amostra_id_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.amostra_id_list.setObjectName(_fromUtf8("amostra_id_list"))
        self.gridLayout.addWidget(self.amostra_id_list, 0, 2, 1, 3)
        self.label_42 = QtGui.QLabel(self.frame)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout.addWidget(self.label_42, 2, 1, 1, 1)
        self.freq_f_list = QtGui.QLabel(self.frame)
        self.freq_f_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.freq_f_list.setObjectName(_fromUtf8("freq_f_list"))
        self.gridLayout.addWidget(self.freq_f_list, 9, 2, 1, 3)
        self.label_43 = QtGui.QLabel(self.frame)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 0, 0, 1, 2)
        self.pasta_list = QtGui.QLabel(self.frame)
        self.pasta_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pasta_list.setObjectName(_fromUtf8("pasta_list"))
        self.gridLayout.addWidget(self.pasta_list, 2, 2, 1, 1)
        self.freq_i_list = QtGui.QLabel(self.frame)
        self.freq_i_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.freq_i_list.setObjectName(_fromUtf8("freq_i_list"))
        self.gridLayout.addWidget(self.freq_i_list, 8, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.frame)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout.addWidget(self.label_46, 9, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.frame)
        self.label_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout.addWidget(self.label_52, 15, 0, 1, 2)
        self.espessura_list = QtGui.QLabel(self.frame)
        self.espessura_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.espessura_list.setObjectName(_fromUtf8("espessura_list"))
        self.gridLayout.addWidget(self.espessura_list, 4, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.frame)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout.addWidget(self.label_47, 10, 1, 1, 1)
        self.media_list = QtGui.QLabel(self.frame)
        self.media_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.media_list.setObjectName(_fromUtf8("media_list"))
        self.gridLayout.addWidget(self.media_list, 15, 2, 1, 3)
        self.label_40 = QtGui.QLabel(self.frame)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 3, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.frame)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 4, 1, 1, 1)
        self.diametro_list = QtGui.QLabel(self.frame)
        self.diametro_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.diametro_list.setObjectName(_fromUtf8("diametro_list"))
        self.gridLayout.addWidget(self.diametro_list, 3, 2, 1, 1)
        self.pontos_list = QtGui.QLabel(self.frame)
        self.pontos_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pontos_list.setObjectName(_fromUtf8("pontos_list"))
        self.gridLayout.addWidget(self.pontos_list, 11, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.frame)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout.addWidget(self.label_48, 11, 1, 1, 1)
        self.banda_list = QtGui.QLabel(self.frame)
        self.banda_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.banda_list.setObjectName(_fromUtf8("banda_list"))
        self.gridLayout.addWidget(self.banda_list, 12, 2, 1, 1)
        self.tensao_list = QtGui.QLabel(self.frame)
        self.tensao_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tensao_list.setObjectName(_fromUtf8("tensao_list"))
        self.gridLayout.addWidget(self.tensao_list, 13, 2, 1, 1)
        self.label_50 = QtGui.QLabel(self.frame)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout.addWidget(self.label_50, 13, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.frame)
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout.addWidget(self.label_49, 12, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.frame)
        self.label_51.setEnabled(True)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout.addWidget(self.label_51, 16, 1, 1, 1)
        self.mpp_list = QtGui.QLabel(self.frame)
        self.mpp_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mpp_list.setObjectName(_fromUtf8("mpp_list"))
        self.gridLayout.addWidget(self.mpp_list, 16, 2, 1, 1)
        self.sweep_list = QtGui.QLabel(self.frame)
        self.sweep_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sweep_list.setObjectName(_fromUtf8("sweep_list"))
        self.gridLayout.addWidget(self.sweep_list, 10, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.frame)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 17, 1, 1, 2)
        self.notas_list = QtGui.QTextBrowser(self.frame)
        self.notas_list.setObjectName(_fromUtf8("notas_list"))
        self.gridLayout.addWidget(self.notas_list, 18, 1, 1, 2)
        self.amostra_id_list.raise_()
        self.label_43.raise_()
        self.freq_f_list.raise_()
        self.label_52.raise_()
        self.media_list.raise_()
        self.label_42.raise_()
        self.pasta_list.raise_()
        self.label_40.raise_()
        self.diametro_list.raise_()
        self.label_41.raise_()
        self.espessura_list.raise_()
        self.label_45.raise_()
        self.freq_i_list.raise_()
        self.label_46.raise_()
        self.label_47.raise_()
        self.sweep_list.raise_()
        self.pontos_list.raise_()
        self.label_48.raise_()
        self.banda_list.raise_()
        self.label_49.raise_()
        self.tensao_list.raise_()
        self.label_50.raise_()
        self.mpp_list.raise_()
        self.label_51.raise_()
        self.label_44.raise_()
        self.notas_list.raise_()
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(350, 480, 141, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.commandLinkButton = QtGui.QCommandLinkButton(self.tab_3)
        self.commandLinkButton.setGeometry(QtCore.QRect(830, 470, 241, 41))
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        MainWindow.setMenuBar(self.menubar)
        self.actionImportar_Dados = QtGui.QAction(MainWindow)
        self.actionImportar_Dados.setObjectName(_fromUtf8("actionImportar_Dados"))
        self.menuArquivo.addAction(self.actionImportar_Dados)
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkbox_ptavg, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spin_ptavg.setEnabled)
        QtCore.QObject.connect(self.checkbox_ptavg, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_10.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Equipment Connection", None))
        self.btn_detectar.setText(_translate("MainWindow", "Detect", None))
        self.checkbox_pyvisasim.setText(_translate("MainWindow", "pyVISA-sim", None))
        self.btn_conectar.setText(_translate("MainWindow", "Connect", None))
        self.label.setText(_translate("MainWindow", "Connected to:", None))
        self.group_calibration.setTitle(_translate("MainWindow", "Compensation", None))
        self.btn_shortcal.setText(_translate("MainWindow", "Short", None))
        self.btn_opencal.setText(_translate("MainWindow", "Open", None))
        self.blt_skipcal.setText(_translate("MainWindow", "Skip", None))
        self.groupBox_analise_2.setTitle(_translate("MainWindow", "Compensation Parameters", None))
        self.label_15.setText(_translate("MainWindow", "Start Frequency:", None))
        self.spin_freq_inicial_2.setSuffix(_translate("MainWindow", " Hz", None))
        self.label_14.setText(_translate("MainWindow", "Stop Frequency:", None))
        self.spin_freq_final_2.setSuffix(_translate("MainWindow", " Hz", None))
        self.label_17.setText(_translate("MainWindow", "Number of Points", None))
        self.label_16.setText(_translate("MainWindow", "Sweep", None))
        self.var_log_2.setText(_translate("MainWindow", "Logarithmic", None))
        self.var_lin_2.setText(_translate("MainWindow", "Linear", None))
        self.label_19.setText(_translate("MainWindow", "Voltage:", None))
        self.spinbox_tensao_2.setSuffix(_translate("MainWindow", " V", None))
        self.label_18.setText(_translate("MainWindow", "Bandwidth:", None))
        self.checkbox_ptavg_2.setText(_translate("MainWindow", "Use Point Average", None))
        self.label_20.setText(_translate("MainWindow", "Measurements per point:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Connection and Compensation", None))
        self.groupBox_analise.setTitle(_translate("MainWindow", "Analysis Parameters", None))
        self.label_4.setText(_translate("MainWindow", "Start Frequency:", None))
        self.spin_freq_inicial.setSuffix(_translate("MainWindow", " Hz", None))
        self.label_5.setText(_translate("MainWindow", "Stop Frequency:", None))
        self.spin_freq_final.setSuffix(_translate("MainWindow", " Hz", None))
        self.label_6.setText(_translate("MainWindow", "Number of Points:", None))
        self.label_7.setText(_translate("MainWindow", "Sweep:", None))
        self.var_log.setText(_translate("MainWindow", "Logarithmic", None))
        self.var_lin.setText(_translate("MainWindow", "Linear", None))
        self.label_8.setText(_translate("MainWindow", "Voltage:", None))
        self.spinbox_tensao.setSuffix(_translate("MainWindow", " V", None))
        self.label_9.setText(_translate("MainWindow", "Bandwidth:", None))
        self.checkbox_ptavg.setText(_translate("MainWindow", "Use Point Average", None))
        self.label_10.setText(_translate("MainWindow", "Measurements per point:", None))
        self.groupBox__amostra.setTitle(_translate("MainWindow", "Sample", None))
        self.label_2.setText(_translate("MainWindow", "Sample Identification", None))
        self.label_3.setText(_translate("MainWindow", "Folder:", None))
        self.toolbtn_savepath.setText(_translate("MainWindow", "...", None))
        self.label_11.setText(_translate("MainWindow", "Diameter(mm):", None))
        self.label_12.setText(_translate("MainWindow", "Thikness(mm):", None))
        self.label_13.setText(_translate("MainWindow", "Notes:", None))
        self.btn_run.setText(_translate("MainWindow", "Start", None))
        self.btn_plot_permi.setText(_translate("MainWindow", "ε\', ε\'\' vs ƒ", None))
        self.btn_plot_ZT.setText(_translate("MainWindow", "Z, Θ vs ƒ", None))
        self.btn_plot_RC.setText(_translate("MainWindow", "R, C vs ƒ", None))
        self.btn_plot_ZrZi.setText(_translate("MainWindow", "Zr vs Zi", None))
        self.btn_plot.setText(_translate("MainWindow", "G", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Analysis", None))
        self.groupBox_analise_3.setTitle(_translate("MainWindow", "Analysis Parameters", None))
        self.label_29.setText(_translate("MainWindow", "Start Frequency:", None))
        self.spin_freq_inicial_4.setSuffix(_translate("MainWindow", " Hz", None))
        self.label_28.setText(_translate("MainWindow", "Stop Frequency:", None))
        self.spin_freq_final_4.setSuffix(_translate("MainWindow", " Hz", None))
        self.label_31.setText(_translate("MainWindow", "Número de Pontos:", None))
        self.label_30.setText(_translate("MainWindow", "Sweep:", None))
        self.var_log_4.setText(_translate("MainWindow", "Logarithmic", None))
        self.var_lin_4.setText(_translate("MainWindow", "Linear", None))
        self.label_33.setText(_translate("MainWindow", "Voltage:", None))
        self.spinbox_tensao_4.setSuffix(_translate("MainWindow", " V", None))
        self.label_32.setText(_translate("MainWindow", "Bandwidth:", None))
        self.checkbox_ptavg_4.setText(_translate("MainWindow", "Use Point Average", None))
        self.label_34.setText(_translate("MainWindow", "Measurements per point:", None))
        self.groupBox__amostra_2.setTitle(_translate("MainWindow", "Sample", None))
        self.label_38.setText(_translate("MainWindow", "Sample Identification", None))
        self.label_37.setText(_translate("MainWindow", "Folder:", None))
        self.toolbtn_savepath_2.setText(_translate("MainWindow", "...", None))
        self.label_35.setText(_translate("MainWindow", "Diameter(mm):", None))
        self.label_36.setText(_translate("MainWindow", "Thickness(mm):", None))
        self.label_39.setText(_translate("MainWindow", "Notes:", None))
        self.label_45.setText(_translate("MainWindow", "Stop Frequency:", None))
        self.amostra_id_list.setText(_translate("MainWindow", "Sample", None))
        self.label_42.setText(_translate("MainWindow", "Folder:", None))
        self.freq_f_list.setText(_translate("MainWindow", "40", None))
        self.label_43.setText(_translate("MainWindow", "Sample Identification", None))
        self.pasta_list.setText(_translate("MainWindow", "Folder", None))
        self.freq_i_list.setText(_translate("MainWindow", "110000000", None))
        self.label_46.setText(_translate("MainWindow", "Start Frequency:", None))
        self.label_52.setText(_translate("MainWindow", "Use Point Average:", None))
        self.espessura_list.setText(_translate("MainWindow", "000000000", None))
        self.label_47.setText(_translate("MainWindow", "Sweep:", None))
        self.media_list.setText(_translate("MainWindow", "Yes", None))
        self.label_40.setText(_translate("MainWindow", "Diameter (mm):", None))
        self.label_41.setText(_translate("MainWindow", "Thickness (mm):", None))
        self.diametro_list.setText(_translate("MainWindow", "0000000", None))
        self.pontos_list.setText(_translate("MainWindow", "0000", None))
        self.label_48.setText(_translate("MainWindow", "Number of Points:", None))
        self.banda_list.setText(_translate("MainWindow", "1", None))
        self.tensao_list.setText(_translate("MainWindow", "00", None))
        self.label_50.setText(_translate("MainWindow", "Voltage:", None))
        self.label_49.setText(_translate("MainWindow", "Bandwidth:", None))
        self.label_51.setText(_translate("MainWindow", "Measurements per point:", None))
        self.mpp_list.setText(_translate("MainWindow", "0000", None))
        self.sweep_list.setText(_translate("MainWindow", "log", None))
        self.label_44.setText(_translate("MainWindow", "Notes:", None))
        self.pushButton.setText(_translate("MainWindow", "Delete Selected", None))
        self.commandLinkButton.setText(_translate("MainWindow", "Start Programmed Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Program Analysis", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "File", None))
        self.actionImportar_Dados.setText(_translate("MainWindow", "Import Data", None))
        self.actionImportar_Dados.setIconText(_translate("MainWindow", "Import Data", None))
        self.actionImportar_Dados.setToolTip(_translate("MainWindow", "Import Data", None))

